#!/bin/sh

configIptables() {
  # change dnsmasq.conf
  sed -i '/server=/d' /etc/dnsmasq.conf
  sed -i '$ a server=127.0.0.1#35353' /etc/dnsmasq.conf
  # Setup the ipse
  ipset -N chnroute hash:net maxelem 65536
  for ip in $(cat '/etc/chinadns/chnroute.txt'); do
    ipset add chnroute $ip
  done
  # 其他请求：
  # shadowsocks
  iptables -t nat -N SHADOWSOCKS
  iptables -t nat -A SHADOWSOCKS -p tcp --dport 33348 -j RETURN
  iptables -t nat -A SHADOWSOCKS -d 103.192.224.12 -j RETURN
  # ignore internal ip
  iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
  iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
  iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
  iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
  iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
  iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
  iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
  iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
  # ignore asia ip
  # Allow connection to chinese IPs
  iptables -t nat -A SHADOWSOCKS -p tcp -m set --match-set chnroute dst -j RETURN
  iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1080
  iptables -t nat -I PREROUTING -p tcp -j SHADOWSOCKS
}
configIptables
